/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormVezbeZaTrening;

import domain.VezbaZaTermin;
import domain.ZakazanTermin;
import forms.MainForm;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import models.TableModelDodajVezbeZaTermin;

/**
 *
 * @author Kujovic
 */
public class FormDodajVezbeZaTrening extends javax.swing.JDialog {

    ZakazanTermin zt;

    public void setZt(ZakazanTermin zt) {
        this.zt = zt;
    }
    /**
     * Creates new form FormDodajVezbeZaTrening
     */
    public FormDodajVezbeZaTrening(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        tblVezbeZaTermin.setModel(new TableModelDodajVezbeZaTermin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDodajVezbu = new javax.swing.JButton();
        txtBrojPonavljanja = new javax.swing.JFormattedTextField();
        lblBrojPonavljanja = new javax.swing.JLabel();
        cbVezba = new javax.swing.JComboBox<>();
        lblVezba = new javax.swing.JLabel();
        btnDodajTermin = new javax.swing.JButton();
        btnObrisiVezbu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVezbeZaTermin = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnDodajVezbu.setText("Dodaj vezbu");
        btnDodajVezbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajVezbuActionPerformed(evt);
            }
        });

        txtBrojPonavljanja.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lblBrojPonavljanja.setText("Broj ponavljanja:");

        cbVezba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sklek", "Cucanj", "Mrtvo dizanje", "Zgib", "Veslo", "T2B", "Izbacaj", "Propadanje", "Benc" }));

        lblVezba.setText("Vezba:");

        btnDodajTermin.setText("Dodaj termin");
        btnDodajTermin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajTerminActionPerformed(evt);
            }
        });

        btnObrisiVezbu.setText("Obrisi vezbu");
        btnObrisiVezbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiVezbuActionPerformed(evt);
            }
        });

        tblVezbeZaTermin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVezbeZaTermin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrojPonavljanja)
                            .addComponent(lblVezba, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVezba, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBrojPonavljanja)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnObrisiVezbu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDodajVezbu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnDodajTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVezba)
                    .addComponent(cbVezba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojPonavljanja)
                    .addComponent(txtBrojPonavljanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodajVezbu)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnObrisiVezbu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodajTermin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajVezbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajVezbuActionPerformed

        
        if(txtBrojPonavljanja.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!");
            return;
        }
        
        String vezba = (String) cbVezba.getSelectedItem();
        int brojPonavljanja = Integer.parseInt(txtBrojPonavljanja.getText());
        
        VezbaZaTermin vzt = new VezbaZaTermin(null, -1, vezba, brojPonavljanja);
        
        TableModelDodajVezbeZaTermin model = 
                (TableModelDodajVezbeZaTermin) tblVezbeZaTermin.getModel();
        model.dodajVezbu(vzt);

    }//GEN-LAST:event_btnDodajVezbuActionPerformed

    private void btnDodajTerminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajTerminActionPerformed

        TableModelDodajVezbeZaTermin model = (TableModelDodajVezbeZaTermin) tblVezbeZaTermin.getModel();
        ArrayList<VezbaZaTermin> vezbeZaTermin = (ArrayList<VezbaZaTermin>) model.getLista();
        
        zt.setVezbeZaTermin(vezbeZaTermin);
        
        MainForm mf = (MainForm) getParent();
        mf.dodajZakazanTermin(zt);
        this.dispose();
        
    }//GEN-LAST:event_btnDodajTerminActionPerformed

    private void btnObrisiVezbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiVezbuActionPerformed
        int selectedRow = tblVezbeZaTermin.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Niste izabrali nijedan red!");
            return;
        }
        
        TableModelDodajVezbeZaTermin model = (TableModelDodajVezbeZaTermin) tblVezbeZaTermin.getModel();
        model.obrisiVezbu(selectedRow);
        
    }//GEN-LAST:event_btnObrisiVezbuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDodajVezbeZaTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDodajVezbeZaTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDodajVezbeZaTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDodajVezbeZaTrening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDodajVezbeZaTrening dialog = new FormDodajVezbeZaTrening(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajTermin;
    private javax.swing.JButton btnDodajVezbu;
    private javax.swing.JButton btnObrisiVezbu;
    private javax.swing.JComboBox<String> cbVezba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrojPonavljanja;
    private javax.swing.JLabel lblVezba;
    private javax.swing.JTable tblVezbeZaTermin;
    private javax.swing.JFormattedTextField txtBrojPonavljanja;
    // End of variables declaration//GEN-END:variables
}
